FROM maven:3-openjdk-8-slim as builder

RUN apt-get -y update && apt-get -y install wget gnupg2
RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
RUN echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
RUN apt-get -y update && apt-get -y install mongodb-org-shell
RUN apt-get clean && rm -rf /var/cache/apt/*


WORKDIR /app
ADD ./target/loggingsystem-0.0.1-SNAPSHOT.jar ./service.jar
CMD java -jar service.jar


